<?php

declare(strict_types=1);

namespace App\Modules\GitHub\Services;

use App\Models\User;
use App\Modules\Projects\Models\Project;
use InvalidArgumentException;

class GitHubExportService
{
    public function __construct(
        protected GitHubClientService $github
    ) {}

    /**
     * Export FORGE blueprints and documentation directly to an isolated branch on GitHub.
     * Enforces safety invariants: never commits to main/master, never force pushes.
     *
     * @return array{success: bool, repo: string, branch: string, branch_url: string, pull_request_url: string, files_committed: array<int, string>}
     */
    public function export(User $user, Project $project, string $repoFullName, ?string $targetBranch = null): array
    {
        $branch = trim($targetBranch ?? '');
        if (empty($branch) || in_array(strtolower($branch), ['main', 'master', 'trunk', 'develop'], true)) {
            $branch = 'forge/blueprint-' . date('Ymd-His');
        }

        // 1. Create the isolated branch from main
        $this->github->createBranch($user, $repoFullName, $branch, 'main');

        // 2. Prepare export files
        $filesToCommit = $this->gatherExportFiles($project, $repoFullName, $branch);
        $committedPaths = [];

        foreach ($filesToCommit as $path => $content) {
            $this->github->commitFile(
                $user,
                $repoFullName,
                $branch,
                $path,
                $content,
                "docs(forge): add {$path} blueprint specifications"
            );
            $committedPaths[] = $path;
        }

        return [
            'success' => true,
            'repo' => $repoFullName,
            'branch' => $branch,
            'branch_url' => "https://github.com/{$repoFullName}/tree/{$branch}",
            'pull_request_url' => "https://github.com/{$repoFullName}/compare/main...{$branch}?expand=1",
            'files_committed' => $committedPaths,
        ];
    }

    /**
     * Gather documents and format blueprint markdown files for export.
     *
     * @return array<string, string>
     */
    protected function gatherExportFiles(Project $project, string $repo, string $branch): array
    {
        $audit = $project->repositoryAudit;
        $files = [];

        // 1. Root FORGE_BLUEPRINT.md
        $blueprint = "# FORGE Growth & Modernization Blueprint\n\n"
            . "> Generated by FORGE Platform for repository: `{$repo}`\n"
            . "> Target Branch: `{$branch}`\n\n"
            . "## Project Overview\n"
            . "- **Title:** {$project->title}\n"
            . "- **Classification:** {$project->classification->label()}\n"
            . "- **Status:** {$project->status->value}\n\n";

        if ($audit) {
            $blueprint .= "## Codebase & Architecture Health\n"
                . "- **Language:** {$audit->primary_language}\n"
                . "- **Framework:** {$audit->detected_framework}\n"
                . "- **Architecture:** {$audit->architecture_pattern}\n"
                . "- **Code Health Score:** {$audit->code_health_score}/100\n"
                . "- **Technical Debt Score:** {$audit->technical_debt_score}/100\n"
                . "- **Security Baseline:** {$audit->security_score}/100\n\n";
        }

        $opportunities = $project->opportunities()->get();
        if ($opportunities->isNotEmpty()) {
            $blueprint .= "## Priority Action Items\n\n";
            foreach ($opportunities as $idx => $opp) {
                $num = $idx + 1;
                $blueprint .= "### {$num}. {$opp->title} [{$opp->quadrant_label}]\n"
                    . "- **Impact:** {$opp->impact} | **Difficulty:** {$opp->difficulty}\n"
                    . "- {$opp->description}\n\n";
            }
        }

        $files['FORGE_BLUEPRINT.md'] = $blueprint;

        // 2. Specific Module Documents
        $docs = $project->documents()->get();
        foreach ($docs as $doc) {
            $docType = $doc->type;
            if ($docType === 'refactor_roadmap') {
                $files['docs/REFACTOR_ROADMAP.md'] = $doc->content;
            } elseif ($docType === 'code_audit') {
                $files['docs/TECHNICAL_DEBT_AUDIT.md'] = $doc->content;
            } elseif ($docType === 'security_audit') {
                $files['docs/SECURITY_AUDIT.md'] = $doc->content;
            } elseif ($docType === 'prd') {
                $files['docs/PRD.md'] = $doc->content;
            } elseif ($docType === 'architecture') {
                $files['docs/ARCHITECTURE.md'] = $doc->content;
            } elseif ($docType === 'growth_plan') {
                $files['docs/GROWTH_PLAN.md'] = $doc->content;
            }
        }

        return $files;
    }
}
