<?php

declare(strict_types=1);

namespace App\Http\Controllers;

use App\Modules\Billing\Contracts\EntitlementServiceInterface;
use App\Modules\Export\Actions\GeneratePdfAction;
use App\Modules\Projects\Models\Project;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;
use ZipArchive;

class ExportController extends Controller
{
    public function __construct(
        protected EntitlementServiceInterface $entitlements,
        protected GeneratePdfAction $generatePdfAction
    ) {}

    public function downloadPackage(Request $request, Project $project): StreamedResponse
    {
        $this->authorize('view', $project);

        if (!$this->entitlements->can($request->user(), 'export.package')) {
            abort(402, 'Upgraded plan required for AI Development Package export.');
        }

        $project->load(['context', 'workflow.stages', 'discovery', 'competitors', 'evidence', 'documents']);

        $filename = 'forge-' . strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $project->title)) . '-package.zip';

        return response()->streamDownload(function () use ($project) {
            $tempZip = tempnam(sys_get_temp_dir(), 'forge_zip_');
            $zip = new ZipArchive();
            $zip->open($tempZip, ZipArchive::CREATE | ZipArchive::OVERWRITE);

            // 1. README.md
            $zip->addFromString('README.md', "# {$project->title}\n\nGenerated by FORGE — Framework for Opportunity, Research, Growth & Execution\n\n## Description\n{$project->description}\n\n## Classification\n{$project->classification->label()}");

            // 2. PRD.md
            $zip->addFromString('PRD.md', "# Product Requirements Document: {$project->title}\n\n## Overview\n{$project->description}\n\n## Target Market\nClassification: {$project->classification->label()}\n\n## Evidence-Linked Requirements\nGenerated with FORGE Intelligence.");

            // 3. Architecture.md
            $zip->addFromString('Architecture.md', "# System Architecture: {$project->title}\n\n## Recommended Architecture\n- Framework: Modern Component-First Stack\n- Classification: {$project->classification->label()}\n- Generated: " . now()->toIso8601String());

            // 4. AGENTS.md
            $zip->addFromString('AGENTS.md', "# Agent Operating Instructions for {$project->title}\n\nAlways follow the architecture and PRD before writing code.\nPreserve modular boundaries and enforce server-side validation.");

            // 5. CLAUDE.md
            $zip->addFromString('CLAUDE.md', "# Claude Instructions for {$project->title}\n\nRead PRD.md and Architecture.md first.\nTest happy paths and failure cases.");

            // 6. MASTER-PROMPT.md
            $zip->addFromString('MASTER-PROMPT.md', "# MASTER PROMPT\n\nYou are an expert engineer tasked with implementing {$project->title}.\nFirst, inspect PRD.md, Architecture.md, and AGENTS.md in order.\nImplement the smallest correct changes and test thoroughly.");

            $zip->close();
            readfile($tempZip);
            @unlink($tempZip);
        }, $filename, [
            'Content-Type' => 'application/zip',
        ]);
    }

    public function downloadPdf(Request $request, Project $project): StreamedResponse
    {
        $this->authorize('view', $project);

        $cleanPdf = $this->entitlements->can($request->user(), 'export.pdf.clean');
        $pdf = $this->generatePdfAction->execute($project, $cleanPdf);

        $filename = 'forge-' . strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $project->title)) . '-blueprint.pdf';

        return response()->streamDownload(function () use ($pdf) {
            echo $pdf->output();
        }, $filename, [
            'Content-Type' => 'application/pdf',
        ]);
    }

    public function downloadGrowthPlanPdf(
        Request $request,
        Project $project,
        \App\Modules\Export\Actions\GenerateGrowthPlanPdfAction $generateAction
    ): StreamedResponse {
        $this->authorize('view', $project);

        $cleanPdf = $this->entitlements->can($request->user(), 'export.pdf.clean');
        $pdf = $generateAction->execute($project, $cleanPdf);

        $filename = 'forge-' . strtolower(preg_replace('/[^a-zA-Z0-9]+/', '-', $project->title)) . '-growth-plan.pdf';

        return response()->streamDownload(function () use ($pdf) {
            echo $pdf->output();
        }, $filename, [
            'Content-Type' => 'application/pdf',
        ]);
    }
}
